import { Property, StatsSummary, CityStats } from "./generated/api.schemas";

export const MOCK_PROPERTIES: Property[] = [
    {
        id: 1,
        title: "Luxury Villa in Cairo",
        titleAr: "فيلا فاخرة في القاهرة",
        description: "Experience premium living with the finest luxury villa in the heart of New Cairo.",
        descriptionAr: "تجربة سكن راقية مع أفخم الفلل في قلب القاهرة الجديدة.",
        type: "sale",
        category: "villa",
        price: 15000000,
        priceUnit: "EGP",
        area: 500,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Fifth Settlement",
        addressAr: "التجمع الخامس",
        lat: 30.0131,
        lng: 31.4089,
        bedrooms: 5,
        bathrooms: 6,
        images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"],
        featured: true,
        amenities: ["Pool", "Gym", "Smart Home"],
        amenitiesAr: ["مسبح", "نادي رياضي", "منزل ذكي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 2,
        title: "Modern Apartment in Alexandria",
        titleAr: "شقة عصرية في الإسكندرية",
        description: "Stunning views of the Mediterranean from this premium modern apartment.",
        descriptionAr: "إطلالات خلابة على البحر المتوسط من هذه الشقة العصرية الراقية.",
        type: "rent",
        category: "apartment",
        price: 25000,
        priceUnit: "EGP/month",
        area: 180,
        country: "Egypt",
        city: "Alexandria",
        cityAr: "الإسكندرية",
        address: "Smouha",
        addressAr: "سموحة",
        lat: 31.2001,
        lng: 29.9187,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"],
        featured: true,
        amenities: ["Balcony", "Security", "Elevator"],
        amenitiesAr: ["بلكونة", "أمن 24/7", "مصعد"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 3,
        title: "Sea View Chalet in Hurghada",
        titleAr: "شاليه مطل على البحر في الغردقة",
        description: "Relax in this peaceful sea view chalet on the Red Sea.",
        descriptionAr: "استرخ في هذا الشاليه الهادئ المطل على البحر الأحمر.",
        type: "sale",
        category: "villa",
        price: 3500000,
        priceUnit: "EGP",
        area: 120,
        country: "Egypt",
        city: "Hurghada",
        cityAr: "الغردقة",
        address: "Sahl Hasheesh",
        addressAr: "سهل حشيش",
        lat: 27.0579,
        lng: 33.8116,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80"],
        featured: false,
        amenities: ["Sea View", "Garden"],
        amenitiesAr: ["إطلالة بحرية", "حديقة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 4,
        title: "Elegant Office in Giza",
        titleAr: "مكتب راقي في الجيزة",
        description: "Start your business in this fully furnished premium office near the Pyramids.",
        descriptionAr: "ابدأ أعمالك في هذا المكتب الفاخر والمفروش بالكامل قرب الأهرامات.",
        type: "rent",
        category: "office",
        price: 45000,
        priceUnit: "EGP/year",
        area: 250,
        country: "Egypt",
        city: "Giza",
        cityAr: "الجيزة",
        address: "Dokki",
        addressAr: "الدقي",
        lat: 30.0131,
        lng: 31.2089,
        bedrooms: 0,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80"],
        featured: true,
        amenities: ["Parking", "Meeting Room", "Reception"],
        amenitiesAr: ["مواقف", "غرفة اجتماعات", "استقبال"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 5,
        title: "Penthouse Suite in Cairo",
        titleAr: "بنتهاوس فاخر في القاهرة",
        description: "Top-floor penthouse with panoramic city views and private rooftop terrace.",
        descriptionAr: "بنتهاوس في الطابق الأخير مع إطلالة بانورامية على المدينة وتراس خاص.",
        type: "sale",
        category: "apartment",
        price: 12000000,
        priceUnit: "EGP",
        area: 380,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Maadi",
        addressAr: "المعادي",
        lat: 30.0131,
        lng: 31.2357,
        bedrooms: 4,
        bathrooms: 4,
        images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80"],
        featured: true,
        amenities: ["Rooftop Terrace", "Concierge", "Gym"],
        amenitiesAr: ["تراس على السطح", "خدمة كونسيرج", "نادي رياضي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 6,
        title: "Family Apartment in Giza",
        titleAr: "شقة عائلية في الجيزة",
        description: "Spacious family apartment near the Pyramids with modern finishes.",
        descriptionAr: "شقة عائلية واسعة قريبة من الأهرامات بتشطيبات حديثة.",
        type: "rent",
        category: "apartment",
        price: 35000,
        priceUnit: "EGP/year",
        area: 200,
        country: "Egypt",
        city: "Giza",
        cityAr: "الجيزة",
        address: "Faisal",
        addressAr: "فيصل",
        lat: 30.0459,
        lng: 31.2386,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80"],
        featured: false,
        amenities: ["Parking", "Playground", "Security"],
        amenitiesAr: ["مواقف سيارات", "ملعب أطفال", "حراسة أمنية"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 7,
        title: "Beachfront Villa in Alexandria",
        titleAr: "فيلا على البحر في الإسكندرية",
        description: "Exclusive beachfront villa with direct access to the Mediterranean.",
        descriptionAr: "فيلا حصرية على الشاطئ مع وصول مباشر للبحر المتوسط.",
        type: "sale",
        category: "villa",
        price: 8000000,
        priceUnit: "EGP",
        area: 520,
        country: "Egypt",
        city: "Alexandria",
        cityAr: "الإسكندرية",
        address: "Miami",
        addressAr: "ميامي",
        lat: 31.2395,
        lng: 29.9664,
        bedrooms: 6,
        bathrooms: 7,
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80"],
        featured: true,
        amenities: ["Private Beach", "Pool", "Garden"],
        amenitiesAr: ["شاطئ خاص", "مسبح", "حديقة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 8,
        title: "Commercial Land in Cairo",
        titleAr: "أرض تجارية في القاهرة",
        description: "Prime commercial land in a strategic location near the Ring Road.",
        descriptionAr: "أرض تجارية ممتازة في موقع استراتيجي قرب الطريق الدائري.",
        type: "sale",
        category: "land",
        price: 25000000,
        priceUnit: "EGP",
        area: 2500,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Nasr City",
        addressAr: "مدينة نصر",
        lat: 30.0444,
        lng: 31.2357,
        bedrooms: 0,
        bathrooms: 0,
        images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80"],
        featured: false,
        amenities: ["Corner Lot", "Main Road Access"],
        amenitiesAr: ["أرض ركنية", "واجهة على الشارع الرئيسي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 9,
        title: "Smart Apartment in New Cairo",
        titleAr: "شقة ذكية في القاهرة الجديدة",
        description: "Futuristic smart apartment in the modern New Cairo district.",
        descriptionAr: "شقة ذكية مستقبلية في حي القاهرة الجديدة الحديث.",
        type: "sale",
        category: "apartment",
        price: 7500000,
        priceUnit: "EGP",
        area: 160,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "New Cairo",
        addressAr: "القاهرة الجديدة",
        lat: 30.0131,
        lng: 31.4089,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80"],
        featured: true,
        amenities: ["Smart Home", "Sustainable Energy", "AI Security"],
        amenitiesAr: ["منزل ذكي", "طاقة مستدامة", "أمن بالذكاء الاصطناعي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 10,
        title: "Luxury Duplex in Giza",
        titleAr: "دوبلكس فاخر في الجيزة",
        description: "Double-floor luxury duplex in the heart of Giza with premium finishes.",
        descriptionAr: "دوبلكس فاخر من طابقين في قلب الجيزة بتشطيبات سوبر لوكس.",
        type: "sale",
        category: "apartment",
        price: 9500000,
        priceUnit: "EGP",
        area: 320,
        country: "Egypt",
        city: "Giza",
        cityAr: "الجيزة",
        address: "6th of October",
        addressAr: "السادس من أكتوبر",
        lat: 29.9792,
        lng: 31.1342,
        bedrooms: 4,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80"],
        featured: false,
        amenities: ["Private Garden", "Garage", "Smart Home"],
        amenitiesAr: ["حديقة خاصة", "جراج", "منزل ذكي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 11,
        title: "Nile View Apartment in Cairo",
        titleAr: "شقة بإطلالة على النيل في القاهرة",
        description: "Breathtaking Nile views from this elegantly designed apartment.",
        descriptionAr: "إطلالات خلابة على النيل من هذه الشقة المصممة بأناقة.",
        type: "rent",
        category: "apartment",
        price: 28000,
        priceUnit: "EGP/month",
        area: 150,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Zamalek",
        addressAr: "الزمالك",
        lat: 30.0444,
        lng: 31.2357,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80"],
        featured: true,
        amenities: ["River View", "Doorman", "Parking"],
        amenitiesAr: ["إطلالة على النيل", "بواب", "جراج"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 12,
        title: "Resort Villa in Sharm El Sheikh",
        titleAr: "فيلا منتجع في شرم الشيخ",
        description: "Private resort-style villa with Red Sea views and private pool.",
        descriptionAr: "فيلا بطراز المنتجعات مع إطلالة على البحر الأحمر ومسبح خاص.",
        type: "sale",
        category: "villa",
        price: 6000000,
        priceUnit: "EGP",
        area: 280,
        country: "Egypt",
        city: "Sharm El Sheikh",
        cityAr: "شرم الشيخ",
        address: "Naama Bay",
        addressAr: "خليج نعمة",
        lat: 27.9158,
        lng: 34.3294,
        bedrooms: 3,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80"],
        featured: false,
        amenities: ["Private Pool", "Sea View", "Furnished"],
        amenitiesAr: ["مسبح خاص", "إطلالة بحرية", "مفروشة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 13,
        title: "Commercial Tower Office in Cairo",
        titleAr: "مكتب في برج تجاري بالقاهرة",
        description: "High-end office space in Cairo's business district.",
        descriptionAr: "مساحة مكتبية راقية في حي الأعمال بالقاهرة.",
        type: "rent",
        category: "office",
        price: 180000,
        priceUnit: "EGP/year",
        area: 400,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Cairo Business District",
        addressAr: "حي الأعمال",
        lat: 30.0444,
        lng: 31.2357,
        bedrooms: 0,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80"],
        featured: true,
        amenities: ["Conference Room", "High Speed Internet", "Valet Parking"],
        amenitiesAr: ["قاعة مؤتمرات", "إنترنت فائق السرعة", "خدمة صف السيارات"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 14,
        title: "Garden Villa in Mansoura",
        titleAr: "فيلا بحديقة في المنصورة",
        description: "Peaceful villa with a large garden in the heart of Mansoura.",
        descriptionAr: "فيلا هادئة بحديقة واسعة في قلب المنصورة.",
        type: "sale",
        category: "villa",
        price: 5500000,
        priceUnit: "EGP",
        area: 600,
        country: "Egypt",
        city: "Mansoura",
        cityAr: "المنصورة",
        address: "Al Gamal",
        addressAr: "الجمال",
        lat: 31.0379,
        lng: 31.3785,
        bedrooms: 7,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1564507593729-f6e2e32c1e27?w=800&q=80"],
        featured: false,
        amenities: ["Large Garden", "Parking", "Quiet Area"],
        amenitiesAr: ["حديقة كبيرة", "مواقف", "منطقة هادئة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 15,
        title: "Studio Apartment in Tanta",
        titleAr: "استوديو في طنطا",
        description: "Cozy furnished studio in the center of Tanta.",
        descriptionAr: "استوديو مفروش ومريح في وسط طنطا.",
        type: "rent",
        category: "apartment",
        price: 8000,
        priceUnit: "EGP/month",
        area: 55,
        country: "Egypt",
        city: "Tanta",
        cityAr: "طنطا",
        address: "Central Area",
        addressAr: "المنطقة المركزية",
        lat: 30.7885,
        lng: 31.0019,
        bedrooms: 1,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80"],
        featured: false,
        amenities: ["Fully Furnished", "Near University"],
        amenitiesAr: ["مفروش بالكامل", "قريب من الجامعة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 16,
        title: "Investment Land in Alexandria",
        titleAr: "أرض استثمارية في الإسكندرية",
        description: "Excellent investment opportunity — residential land in Alexandria.",
        descriptionAr: "فرصة استثمارية ممتازة — أرض سكنية في الإسكندرية.",
        type: "sale",
        category: "land",
        price: 12000000,
        priceUnit: "EGP",
        area: 800,
        country: "Egypt",
        city: "Alexandria",
        cityAr: "الإسكندرية",
        address: "Borg El Arab",
        addressAr: "برج العرب",
        lat: 31.2001,
        lng: 29.9187,
        bedrooms: 0,
        bathrooms: 0,
        images: ["https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80"],
        featured: false,
        amenities: ["Residential Zoning", "Near Highway"],
        amenitiesAr: ["تصنيف سكني", "قريب من الطريق السريع"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 17,
        title: "Waterfront Apartment in Port Said",
        titleAr: "شقة على الواجهة البحرية في بورسعيد",
        description: "Modern apartment overlooking the waterfront promenade in Port Said.",
        descriptionAr: "شقة حديثة تطل على الممشى البحري في بورسعيد.",
        type: "rent",
        category: "apartment",
        price: 22000,
        priceUnit: "EGP/year",
        area: 170,
        country: "Egypt",
        city: "Port Said",
        cityAr: "بورسعيد",
        address: "Waterfront",
        addressAr: "الواجهة البحرية",
        lat: 31.2653,
        lng: 32.3019,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=800&q=80"],
        featured: false,
        amenities: ["Waterfront View", "Gym", "Pool"],
        amenitiesAr: ["إطلالة بحرية", "نادي رياضي", "مسبح"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 18,
        title: "Luxury Compound Villa in Cairo",
        titleAr: "فيلا كمبوند فاخرة في القاهرة",
        description: "Gated compound villa with world-class amenities and 24/7 security.",
        descriptionAr: "فيلا داخل كمبوند محاط بالأسوار مع خدمات عالمية المستوى وأمن على مدار الساعة.",
        type: "rent",
        category: "villa",
        price: 250000,
        priceUnit: "EGP/year",
        area: 350,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Katameya Heights",
        addressAr: "كاتاميا هايتس",
        lat: 30.0131,
        lng: 31.4089,
        bedrooms: 4,
        bathrooms: 4,
        images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80"],
        featured: true,
        amenities: ["Compound", "24/7 Security", "Pool", "Tennis Court"],
        amenitiesAr: ["كمبوند", "أمن 24/7", "مسبح", "ملعب تنس"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 19,
        title: "Commercial Shop in Giza",
        titleAr: "محل تجاري في الجيزة",
        description: "High-traffic commercial shop in downtown Giza, ideal for retail.",
        descriptionAr: "محل تجاري في وسط الجيزة بحركة مرور عالية، مثالي للبيع بالتجزئة.",
        type: "rent",
        category: "commercial",
        price: 45000,
        priceUnit: "EGP/month",
        area: 90,
        country: "Egypt",
        city: "Giza",
        cityAr: "الجيزة",
        address: "Downtown Giza",
        addressAr: "وسط البلد",
        lat: 30.0131,
        lng: 31.2089,
        bedrooms: 0,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80"],
        featured: false,
        amenities: ["Street Facing", "Storage Room"],
        amenitiesAr: ["واجهة على الشارع", "مخزن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 20,
        title: "Twin Villa in Alexandria",
        titleAr: "فيلا توين في الإسكندرية",
        description: "Elegant twin villa with premium design in Alexandria's finest neighborhood.",
        descriptionAr: "فيلا توين أنيقة بتصميم راقي في أفضل أحياء الإسكندرية.",
        type: "sale",
        category: "villa",
        price: 7000000,
        priceUnit: "EGP",
        area: 380,
        country: "Egypt",
        city: "Alexandria",
        cityAr: "الإسكندرية",
        address: "Glim",
        addressAr: "الجليم",
        lat: 31.2395,
        lng: 29.9664,
        bedrooms: 5,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80"],
        featured: false,
        amenities: ["Driver Room", "Maid Room", "Garden"],
        amenitiesAr: ["غرفة سائق", "غرفة خادمة", "حديقة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 21,
        title: "Modern Loft in Cairo",
        titleAr: "لوفت عصري في القاهرة",
        description: "Stylish open-plan loft in the vibrant heart of Cairo.",
        descriptionAr: "لوفت أنيق بتصميم مفتوح في قلب القاهرة النابض بالحياة.",
        type: "rent",
        category: "apartment",
        price: 20000,
        priceUnit: "EGP/month",
        area: 110,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Downtown Cairo",
        addressAr: "وسط البلد",
        lat: 30.0459,
        lng: 31.2386,
        bedrooms: 1,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80"],
        featured: false,
        amenities: ["Open Plan", "High Ceiling", "Furnished"],
        amenitiesAr: ["تصميم مفتوح", "سقف عالي", "مفروش"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 22,
        title: "Executive Suite in Ismailia",
        titleAr: "جناح تنفيذي في الإسماعيلية",
        description: "Fully serviced executive apartment in a 5-star building.",
        descriptionAr: "شقة تنفيذية مخدومة بالكامل في مبنى 5 نجوم.",
        type: "rent",
        category: "apartment",
        price: 15000,
        priceUnit: "EGP/year",
        area: 140,
        country: "Egypt",
        city: "Ismailia",
        cityAr: "الإسماعيلية",
        address: "Central Area",
        addressAr: "المنطقة المركزية",
        lat: 30.6043,
        lng: 32.2722,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80"],
        featured: false,
        amenities: ["Room Service", "Business Center", "Valet"],
        amenitiesAr: ["خدمة الغرف", "مركز أعمال", "خدمة صف السيارات"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 23,
        title: "Pyramids View Villa in Giza",
        titleAr: "فيلا بإطلالة على الأهرامات في الجيزة",
        description: "Once-in-a-lifetime opportunity — villa with direct Pyramids views.",
        descriptionAr: "فرصة العمر — فيلا بإطلالة مباشرة على الأهرامات.",
        type: "sale",
        category: "villa",
        price: 20000000,
        priceUnit: "EGP",
        area: 500,
        country: "Egypt",
        city: "Giza",
        cityAr: "الجيزة",
        address: "Haram Road",
        addressAr: "شارع الهرم",
        lat: 29.9792,
        lng: 31.1342,
        bedrooms: 6,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80"],
        featured: true,
        amenities: ["Pyramids View", "Pool", "Private Garden", "Security"],
        amenitiesAr: ["إطلالة على الأهرامات", "مسبح", "حديقة خاصة", "حراسة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 24,
        title: "Medical Office in Cairo",
        titleAr: "عيادة طبية في القاهرة",
        description: "Licensed medical office space in a healthcare complex.",
        descriptionAr: "عيادة طبية مرخصة في مجمع طبي متكامل.",
        type: "rent",
        category: "office",
        price: 120000,
        priceUnit: "EGP/year",
        area: 180,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Heliopolis",
        addressAr: "مصر الجديدة",
        lat: 30.0849,
        lng: 31.3249,
        bedrooms: 0,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80"],
        featured: false,
        amenities: ["Medical License", "Waiting Area", "Elevator"],
        amenitiesAr: ["رخصة طبية", "صالة انتظار", "مصعد"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 25,
        title: "Modern Villa in Dakahlia",
        titleAr: "فيلا عصرية في الدقهلية",
        description: "Spacious modern villa in the heart of Dakahlia.",
        descriptionAr: "فيلا عصرية واسعة في قلب الدقهلية.",
        type: "sale",
        category: "villa",
        price: 4500000,
        priceUnit: "EGP",
        area: 400,
        country: "Egypt",
        city: "Mansoura",
        cityAr: "المنصورة",
        address: "Mansoura",
        addressAr: "المنصورة",
        lat: 31.0379,
        lng: 31.3785,
        bedrooms: 5,
        bathrooms: 4,
        images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
        featured: false,
        amenities: ["Garden", "Parking", "Security"],
        amenitiesAr: ["حديقة", "مواقف", "أمن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 26,
        title: "Beach House in Beheira",
        titleAr: "بيت شاطئي في البحيرة",
        description: "Beautiful beach house in Beheira governorate.",
        descriptionAr: "بيت شاطئي جميل في محافظة البحيرة.",
        type: "sale",
        category: "villa",
        price: 3200000,
        priceUnit: "EGP",
        area: 250,
        country: "Egypt",
        city: "Damanhour",
        cityAr: "دمنهور",
        address: "Damanhour",
        addressAr: "دمنهور",
        lat: 31.0364,
        lng: 30.4783,
        bedrooms: 4,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80"],
        featured: false,
        amenities: ["Sea View", "Garden", "Parking"],
        amenitiesAr: ["إطلالة بحرية", "حديقة", "مواقف"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 27,
        title: "Apartment in Fayoum",
        titleAr: "شقة في الفيوم",
        description: "Comfortable apartment in Fayoum city.",
        descriptionAr: "شقة مريحة في مدينة الفيوم.",
        type: "rent",
        category: "apartment",
        price: 6000,
        priceUnit: "EGP/month",
        area: 120,
        country: "Egypt",
        city: "Fayoum",
        cityAr: "الفيوم",
        address: "Fayoum City",
        addressAr: "مدينة الفيوم",
        lat: 29.3075,
        lng: 30.8428,
        bedrooms: 2,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"],
        featured: false,
        amenities: ["Balcony", "Elevator"],
        amenitiesAr: ["بلكونة", "مصعد"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 28,
        title: "Commercial Space in Gharbia",
        titleAr: "مساحة تجارية في الغربية",
        description: "Prime commercial space in Gharbia.",
        descriptionAr: "مساحة تجارية ممتازة في الغربية.",
        type: "rent",
        category: "commercial",
        price: 25000,
        priceUnit: "EGP/year",
        area: 150,
        country: "Egypt",
        city: "Tanta",
        cityAr: "طنطا",
        address: "Tanta",
        addressAr: "طنطا",
        lat: 30.7885,
        lng: 31.0019,
        bedrooms: 0,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80"],
        featured: false,
        amenities: ["Street Front", "Storage"],
        amenitiesAr: ["واجهة شارع", "مخزن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 29,
        title: "Villa in Monufia",
        titleAr: "فيلا في المنوفية",
        description: "Elegant villa in Monufia governorate.",
        descriptionAr: "فيلا أنيقة في محافظة المنوفية.",
        type: "sale",
        category: "villa",
        price: 3800000,
        priceUnit: "EGP",
        area: 350,
        country: "Egypt",
        city: "Shebin El Kom",
        cityAr: "شبين الكوم",
        address: "Shebin El Kom",
        addressAr: "شبين الكوم",
        lat: 30.4403,
        lng: 31.0091,
        bedrooms: 5,
        bathrooms: 4,
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80"],
        featured: false,
        amenities: ["Garden", "Garage", "Security"],
        amenitiesAr: ["حديقة", "جراج", "أمن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 30,
        title: "Apartment in Minya",
        titleAr: "شقة في المنيا",
        description: "Modern apartment in Minya city.",
        descriptionAr: "شقة حديثة في مدينة المنيا.",
        type: "sale",
        category: "apartment",
        price: 1800000,
        priceUnit: "EGP",
        area: 140,
        country: "Egypt",
        city: "Minya",
        cityAr: "المنيا",
        address: "Minya City",
        addressAr: "مدينة المنيا",
        lat: 28.1087,
        lng: 30.7504,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80"],
        featured: false,
        amenities: ["Balcony", "Elevator", "Security"],
        amenitiesAr: ["بلكونة", "مصعد", "أمن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 31,
        title: "Office in Qalyubia",
        titleAr: "مكتب في القليوبية",
        description: "Professional office space in Qalyubia.",
        descriptionAr: "مساحة مكتبية احترافية في القليوبية.",
        type: "rent",
        category: "office",
        price: 35000,
        priceUnit: "EGP/year",
        area: 100,
        country: "Egypt",
        city: "Banha",
        cityAr: "بنها",
        address: "Banha",
        addressAr: "بنها",
        lat: 30.4664,
        lng: 31.1782,
        bedrooms: 0,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80"],
        featured: false,
        amenities: ["AC", "Parking", "Elevator"],
        amenitiesAr: ["تكييف", "مواقف", "مصعد"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 32,
        title: "Land in New Valley",
        titleAr: "أرض في الوادي الجديد",
        description: "Agricultural land in New Valley governorate.",
        descriptionAr: "أرض زراعية في محافظة الوادي الجديد.",
        type: "sale",
        category: "land",
        price: 800000,
        priceUnit: "EGP",
        area: 5000,
        country: "Egypt",
        city: "Kharga",
        cityAr: "الخارجة",
        address: "Kharga Oasis",
        addressAr: "واحة الخارجة",
        lat: 25.4516,
        lng: 30.5464,
        bedrooms: 0,
        bathrooms: 0,
        images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80"],
        featured: false,
        amenities: ["Agricultural", "Water Well"],
        amenitiesAr: ["زراعي", "بئر ماء"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 33,
        title: "Apartment in Suez",
        titleAr: "شقة في السويس",
        description: "Modern apartment in Suez city.",
        descriptionAr: "شقة حديثة في مدينة السويس.",
        type: "rent",
        category: "apartment",
        price: 9000,
        priceUnit: "EGP/month",
        area: 110,
        country: "Egypt",
        city: "Suez",
        cityAr: "السويس",
        address: "Suez City",
        addressAr: "مدينة السويس",
        lat: 29.9737,
        lng: 32.5263,
        bedrooms: 2,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80"],
        featured: false,
        amenities: ["Sea View", "Balcony"],
        amenitiesAr: ["إطلالة بحرية", "بلكونة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 34,
        title: "Villa in Aswan",
        titleAr: "فيلا في أسوان",
        description: "Luxury villa with Nile view in Aswan.",
        descriptionAr: "فيلا فاخرة بإطلالة على النيل في أسوان.",
        type: "sale",
        category: "villa",
        price: 5500000,
        priceUnit: "EGP",
        area: 450,
        country: "Egypt",
        city: "Aswan",
        cityAr: "أسوان",
        address: "Aswan City",
        addressAr: "مدينة أسوان",
        lat: 24.0889,
        lng: 32.8998,
        bedrooms: 6,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80"],
        featured: true,
        amenities: ["Nile View", "Pool", "Garden"],
        amenitiesAr: ["إطلالة على النيل", "مسبح", "حديقة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 35,
        title: "Apartment in Assiut",
        titleAr: "شقة في أسيوط",
        description: "Affordable apartment in Assiut city.",
        descriptionAr: "شقة اقتصادية في مدينة أسيوط.",
        type: "sale",
        category: "apartment",
        price: 1200000,
        priceUnit: "EGP",
        area: 100,
        country: "Egypt",
        city: "Assiut",
        cityAr: "أسيوط",
        address: "Assiut City",
        addressAr: "مدينة أسيوط",
        lat: 27.1806,
        lng: 31.1837,
        bedrooms: 2,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"],
        featured: false,
        amenities: ["Balcony", "Elevator"],
        amenitiesAr: ["بلكونة", "مصعد"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 36,
        title: "Villa in Beni Suef",
        titleAr: "فيلا في بني سويف",
        description: "Spacious villa in Beni Suef governorate.",
        descriptionAr: "فيلا واسعة في محافظة بني سويف.",
        type: "sale",
        category: "villa",
        price: 2800000,
        priceUnit: "EGP",
        area: 320,
        country: "Egypt",
        city: "Beni Suef",
        cityAr: "بني سويف",
        address: "Beni Suef City",
        addressAr: "مدينة بني سويف",
        lat: 29.0644,
        lng: 31.0979,
        bedrooms: 4,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80"],
        featured: false,
        amenities: ["Garden", "Parking", "Security"],
        amenitiesAr: ["حديقة", "مواقف", "أمن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 37,
        title: "Commercial Shop in Damietta",
        titleAr: "محل تجاري في دمياط",
        description: "High-traffic commercial shop in Damietta.",
        descriptionAr: "محل تجاري بحركة مرور عالية في دمياط.",
        type: "rent",
        category: "commercial",
        price: 30000,
        priceUnit: "EGP/year",
        area: 80,
        country: "Egypt",
        city: "Damietta",
        cityAr: "دمياط",
        address: "Damietta City",
        addressAr: "مدينة دمياط",
        lat: 31.4165,
        lng: 31.8133,
        bedrooms: 0,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80"],
        featured: false,
        amenities: ["Street Front", "Storage"],
        amenitiesAr: ["واجهة شارع", "مخزن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 38,
        title: "Apartment in Sharkia",
        titleAr: "شقة في الشرقية",
        description: "Modern apartment in Sharkia governorate.",
        descriptionAr: "شقة حديثة في محافظة الشرقية.",
        type: "rent",
        category: "apartment",
        price: 7000,
        priceUnit: "EGP/month",
        area: 130,
        country: "Egypt",
        city: "Zagazig",
        cityAr: "الزقازيق",
        address: "Zagazig",
        addressAr: "الزقازيق",
        lat: 30.5877,
        lng: 31.3825,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80"],
        featured: false,
        amenities: ["Balcony", "Elevator"],
        amenitiesAr: ["بلكونة", "مصعد"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 39,
        title: "Resort in South Sinai",
        titleAr: "منتجع في جنوب سيناء",
        description: "Luxury resort in South Sinai.",
        descriptionAr: "منتجع فاخر في جنوب سيناء.",
        type: "sale",
        category: "villa",
        price: 8500000,
        priceUnit: "EGP",
        area: 600,
        country: "Egypt",
        city: "Sharm El Sheikh",
        cityAr: "شرم الشيخ",
        address: "Shark Bay",
        addressAr: "خليج القرش",
        lat: 27.9158,
        lng: 34.3294,
        bedrooms: 7,
        bathrooms: 6,
        images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80"],
        featured: true,
        amenities: ["Private Beach", "Pool", "Spa"],
        amenitiesAr: ["شاطئ خاص", "مسبح", "سبا"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 40,
        title: "Villa in Kafr El Sheikh",
        titleAr: "فيلا في كفر الشيخ",
        description: "Beautiful villa in Kafr El Sheikh.",
        descriptionAr: "فيلا جميلة في كفر الشيخ.",
        type: "sale",
        category: "villa",
        price: 3200000,
        priceUnit: "EGP",
        area: 380,
        country: "Egypt",
        city: "Kafr El Sheikh",
        cityAr: "كفر الشيخ",
        address: "Kafr El Sheikh City",
        addressAr: "مدينة كفر الشيخ",
        lat: 31.1106,
        lng: 30.9389,
        bedrooms: 5,
        bathrooms: 4,
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80"],
        featured: false,
        amenities: ["Garden", "Parking", "Security"],
        amenitiesAr: ["حديقة", "مواقف", "أمن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 41,
        title: "Beach Villa in Matrouh",
        titleAr: "فيلا شاطئية في مطروح",
        description: "Stunning beach villa in Matrouh.",
        descriptionAr: "فيلا شاطئية خلابة في مطروح.",
        type: "sale",
        category: "villa",
        price: 9500000,
        priceUnit: "EGP",
        area: 550,
        country: "Egypt",
        city: "Marsa Matrouh",
        cityAr: "مرسى مطروح",
        address: "Cleopatra Beach",
        addressAr: "شاطئ كليوباترا",
        lat: 31.3536,
        lng: 27.2664,
        bedrooms: 6,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80"],
        featured: true,
        amenities: ["Private Beach", "Pool", "Sea View"],
        amenitiesAr: ["شاطئ خاص", "مسبح", "إطلالة بحرية"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 42,
        title: "Apartment in Luxor",
        titleAr: "شقة في الأقصر",
        description: "Apartment with Nile view in Luxor.",
        descriptionAr: "شقة بإطلالة على النيل في الأقصر.",
        type: "rent",
        category: "apartment",
        price: 5000,
        priceUnit: "EGP/month",
        area: 90,
        country: "Egypt",
        city: "Luxor",
        cityAr: "الأقصر",
        address: "Luxor City",
        addressAr: "مدينة الأقصر",
        lat: 25.6872,
        lng: 32.6496,
        bedrooms: 2,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80"],
        featured: false,
        amenities: ["Nile View", "Balcony"],
        amenitiesAr: ["إطلالة على النيل", "بلكونة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 43,
        title: "Villa in Qena",
        titleAr: "فيلا في قنا",
        description: "Spacious villa in Qena governorate.",
        descriptionAr: "فيلا واسعة في محافظة قنا.",
        type: "sale",
        category: "villa",
        price: 2200000,
        priceUnit: "EGP",
        area: 300,
        country: "Egypt",
        city: "Qena",
        cityAr: "قنا",
        address: "Qena City",
        addressAr: "مدينة قنا",
        lat: 26.0984,
        lng: 32.7346,
        bedrooms: 4,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
        featured: false,
        amenities: ["Garden", "Parking"],
        amenitiesAr: ["حديقة", "مواقف"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 44,
        title: "Apartment in North Sinai",
        titleAr: "شقة في شمال سيناء",
        description: "Modern apartment in North Sinai.",
        descriptionAr: "شقة حديثة في شمال سيناء.",
        type: "rent",
        category: "apartment",
        price: 8000,
        priceUnit: "EGP/month",
        area: 120,
        country: "Egypt",
        city: "Arish",
        cityAr: "العريش",
        address: "Arish",
        addressAr: "العريش",
        lat: 31.1334,
        lng: 33.7979,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=800&q=80"],
        featured: false,
        amenities: ["Balcony", "Security"],
        amenitiesAr: ["بلكونة", "أمن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 45,
        title: "Commercial Space in Sohag",
        titleAr: "مساحة تجارية في سوهاج",
        description: "Commercial space in Sohag city.",
        descriptionAr: "مساحة تجارية في مدينة سوهاج.",
        type: "rent",
        category: "commercial",
        price: 20000,
        priceUnit: "EGP/year",
        area: 120,
        country: "Egypt",
        city: "Sohag",
        cityAr: "سوهاج",
        address: "Sohag City",
        addressAr: "مدينة سوهاج",
        lat: 26.5565,
        lng: 31.6948,
        bedrooms: 0,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80"],
        featured: false,
        amenities: ["Street Front", "Storage"],
        amenitiesAr: ["واجهة شارع", "مخزن"],
        createdAt: new Date().toISOString(),
    },
];

export const MOCK_STATS_SUMMARY: StatsSummary = {
    totalProperties: MOCK_PROPERTIES.length,
    forSale: MOCK_PROPERTIES.filter(p => p.type === 'sale').length,
    forRent: MOCK_PROPERTIES.filter(p => p.type === 'rent').length,
    avgPriceSale: Math.round(MOCK_PROPERTIES.filter(p => p.type === 'sale').reduce((a, b) => a + b.price, 0) / Math.max(MOCK_PROPERTIES.filter(p => p.type === 'sale').length, 1)),
    avgPriceRent: Math.round(MOCK_PROPERTIES.filter(p => p.type === 'rent').reduce((a, b) => a + b.price, 0) / Math.max(MOCK_PROPERTIES.filter(p => p.type === 'rent').length, 1)),
    totalCities: new Set(MOCK_PROPERTIES.map(p => p.city)).size,
    newThisMonth: MOCK_PROPERTIES.length,
};

export const MOCK_CITIES: CityStats[] = Array.from(new Set(MOCK_PROPERTIES.map(p => p.city))).map(city => {
    const prop = MOCK_PROPERTIES.find(p => p.city === city)!;
    return {
        city: prop.city,
        cityAr: prop.cityAr,
        count: MOCK_PROPERTIES.filter(p => p.city === city).length
    };
});
