import { Property, StatsSummary, CityStats } from "./generated/api.schemas";

export const MOCK_PROPERTIES: Property[] = [
    {
        id: 1,
        title: "Luxury Villa in Riyadh",
        titleAr: "فيلا فاخرة في الرياض",
        description: "Experience premium living with the finest luxury villa in the heart of Riyadh.",
        descriptionAr: "تجربة سكن راقية مع أفخم الفلل في قلب مدينة الرياض.",
        type: "sale",
        category: "villa",
        price: 5000000,
        priceUnit: "SAR",
        area: 450,
        country: "Saudi Arabia",
        city: "Riyadh",
        cityAr: "الرياض",
        address: "Al Malqa District",
        addressAr: "حي الملقا",
        lat: 24.7136,
        lng: 46.6753,
        bedrooms: 5,
        bathrooms: 6,
        images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"],
        featured: true,
        amenities: ["Pool", "Gym", "Smart Home"],
        amenitiesAr: ["مسبح", "نادي رياضي", "منزل ذكي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 2,
        title: "Modern Apartment in Cairo",
        titleAr: "شقة عصرية في القاهرة",
        description: "Stunning views of the Nile from this premium modern apartment.",
        descriptionAr: "إطلالات خلابة على النيل من هذه الشقة العصرية الراقية.",
        type: "rent",
        category: "apartment",
        price: 25000,
        priceUnit: "EGP/month",
        area: 180,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Zamalek",
        addressAr: "الزمالك",
        lat: 30.0444,
        lng: 31.2357,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"],
        featured: true,
        amenities: ["Balcony", "Security", "Elevator"],
        amenitiesAr: ["بلكونة", "أمن 24/7", "مصعد"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 3,
        title: "Sea View Chalet in Alexandria",
        titleAr: "شاليه مطل على البحر في الإسكندرية",
        description: "Relax in this peaceful sea view chalet on the Mediterranean sea.",
        descriptionAr: "استرخ في هذا الشاليه الهادئ المطل على البحر المتوسط.",
        type: "sale",
        category: "villa",
        price: 3500000,
        priceUnit: "EGP",
        area: 120,
        country: "Egypt",
        city: "Alexandria",
        cityAr: "الإسكندرية",
        address: "Al Luran",
        addressAr: "لوران",
        lat: 31.2001,
        lng: 29.9187,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80"],
        featured: false,
        amenities: ["Sea View", "Garden"],
        amenitiesAr: ["إطلالة بحرية", "حديقة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 4,
        title: "Elegant Office in Jeddah",
        titleAr: "مكتب راقي في جدة",
        description: "Start your business in this fully furnished premium office.",
        descriptionAr: "ابدأ أعمالك في هذا المكتب الفاخر والمفروش بالكامل.",
        type: "rent",
        category: "office",
        price: 45000,
        priceUnit: "SAR/year",
        area: 250,
        country: "Saudi Arabia",
        city: "Jeddah",
        cityAr: "جدة",
        address: "Al Shatea",
        addressAr: "الشاطئ",
        lat: 21.4858,
        lng: 39.1925,
        bedrooms: 0,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80"],
        featured: true,
        amenities: ["Parking", "Meeting Room", "Reception"],
        amenitiesAr: ["مواقف", "غرفة اجتماعات", "استقبال"],
        createdAt: new Date().toISOString(),
    },
    // --- 20 عقار إضافي ---
    {
        id: 5,
        title: "Penthouse Suite in Riyadh",
        titleAr: "بنتهاوس فاخر في الرياض",
        description: "Top-floor penthouse with panoramic city views and private rooftop terrace.",
        descriptionAr: "بنتهاوس في الطابق الأخير مع إطلالة بانورامية على المدينة وتراس خاص.",
        type: "sale",
        category: "apartment",
        price: 8500000,
        priceUnit: "SAR",
        area: 380,
        country: "Saudi Arabia",
        city: "Riyadh",
        cityAr: "الرياض",
        address: "Al Olaya District",
        addressAr: "حي العليا",
        lat: 24.6908,
        lng: 46.6855,
        bedrooms: 4,
        bathrooms: 4,
        images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80"],
        featured: true,
        amenities: ["Rooftop Terrace", "Concierge", "Gym"],
        amenitiesAr: ["تراس على السطح", "خدمة كونسيرج", "نادي رياضي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 6,
        title: "Family Apartment in Jeddah",
        titleAr: "شقة عائلية في جدة",
        description: "Spacious family apartment near Al Balad with modern finishes.",
        descriptionAr: "شقة عائلية واسعة قريبة من البلد بتشطيبات حديثة.",
        type: "rent",
        category: "apartment",
        price: 55000,
        priceUnit: "SAR/year",
        area: 200,
        country: "Saudi Arabia",
        city: "Jeddah",
        cityAr: "جدة",
        address: "Al Rawdah",
        addressAr: "الروضة",
        lat: 21.5433,
        lng: 39.1728,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80"],
        featured: false,
        amenities: ["Parking", "Playground", "Security"],
        amenitiesAr: ["مواقف سيارات", "ملعب أطفال", "حراسة أمنية"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 7,
        title: "Beachfront Villa in Khobar",
        titleAr: "فيلا على البحر في الخبر",
        description: "Exclusive beachfront villa with direct access to the Arabian Gulf.",
        descriptionAr: "فيلا حصرية على الشاطئ مع وصول مباشر للخليج العربي.",
        type: "sale",
        category: "villa",
        price: 7200000,
        priceUnit: "SAR",
        area: 520,
        country: "Saudi Arabia",
        city: "Khobar",
        cityAr: "الخبر",
        address: "Corniche Road",
        addressAr: "طريق الكورنيش",
        lat: 26.2172,
        lng: 50.1971,
        bedrooms: 6,
        bathrooms: 7,
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80"],
        featured: true,
        amenities: ["Private Beach", "Pool", "Garden"],
        amenitiesAr: ["شاطئ خاص", "مسبح", "حديقة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 8,
        title: "Commercial Land in Dammam",
        titleAr: "أرض تجارية في الدمام",
        description: "Prime commercial land in a strategic location near King Fahd Road.",
        descriptionAr: "أرض تجارية ممتازة في موقع استراتيجي قرب طريق الملك فهد.",
        type: "sale",
        category: "land",
        price: 12000000,
        priceUnit: "SAR",
        area: 2500,
        country: "Saudi Arabia",
        city: "Dammam",
        cityAr: "الدمام",
        address: "King Fahd Road",
        addressAr: "طريق الملك فهد",
        lat: 26.3927,
        lng: 49.9777,
        bedrooms: 0,
        bathrooms: 0,
        images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80"],
        featured: false,
        amenities: ["Corner Lot", "Main Road Access"],
        amenitiesAr: ["أرض ركنية", "واجهة على الشارع الرئيسي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 9,
        title: "Smart Apartment in NEOM",
        titleAr: "شقة ذكية في نيوم",
        description: "Futuristic smart apartment in the revolutionary NEOM city.",
        descriptionAr: "شقة ذكية مستقبلية في مدينة نيوم الثورية.",
        type: "sale",
        category: "apartment",
        price: 4200000,
        priceUnit: "SAR",
        area: 160,
        country: "Saudi Arabia",
        city: "NEOM",
        cityAr: "نيوم",
        address: "The Line District",
        addressAr: "حي ذا لاين",
        lat: 27.9506,
        lng: 35.5647,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80"],
        featured: true,
        amenities: ["Smart Home", "Sustainable Energy", "AI Security"],
        amenitiesAr: ["منزل ذكي", "طاقة مستدامة", "أمن بالذكاء الاصطناعي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 10,
        title: "Luxury Duplex in Cairo",
        titleAr: "دوبلكس فاخر في القاهرة",
        description: "Double-floor luxury duplex in the heart of New Cairo with premium finishes.",
        descriptionAr: "دوبلكس فاخر من طابقين في قلب القاهرة الجديدة بتشطيبات سوبر لوكس.",
        type: "sale",
        category: "apartment",
        price: 6800000,
        priceUnit: "EGP",
        area: 320,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Fifth Settlement",
        addressAr: "التجمع الخامس",
        lat: 30.0131,
        lng: 31.4089,
        bedrooms: 4,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80"],
        featured: false,
        amenities: ["Private Garden", "Garage", "Smart Home"],
        amenitiesAr: ["حديقة خاصة", "جراج", "منزل ذكي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 11,
        title: "Nile View Apartment in Giza",
        titleAr: "شقة بإطلالة على النيل في الجيزة",
        description: "Breathtaking Nile and Pyramid views from this elegantly designed apartment.",
        descriptionAr: "إطلالات خلابة على النيل والأهرامات من هذه الشقة المصممة بأناقة.",
        type: "rent",
        category: "apartment",
        price: 18000,
        priceUnit: "EGP/month",
        area: 150,
        country: "Egypt",
        city: "Giza",
        cityAr: "الجيزة",
        address: "Corniche El Nil",
        addressAr: "كورنيش النيل",
        lat: 30.0131,
        lng: 31.2089,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80"],
        featured: true,
        amenities: ["River View", "Doorman", "Parking"],
        amenitiesAr: ["إطلالة على النيل", "بواب", "جراج"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 12,
        title: "Resort Villa in Hurghada",
        titleAr: "فيلا منتجع في الغردقة",
        description: "Private resort-style villa with Red Sea views and private pool.",
        descriptionAr: "فيلا بطراز المنتجعات مع إطلالة على البحر الأحمر ومسبح خاص.",
        type: "sale",
        category: "villa",
        price: 4500000,
        priceUnit: "EGP",
        area: 280,
        country: "Egypt",
        city: "Hurghada",
        cityAr: "الغردقة",
        address: "Sahl Hasheesh",
        addressAr: "سهل حشيش",
        lat: 27.0579,
        lng: 33.8116,
        bedrooms: 3,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80"],
        featured: false,
        amenities: ["Private Pool", "Sea View", "Furnished"],
        amenitiesAr: ["مسبح خاص", "إطلالة بحرية", "مفروشة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 13,
        title: "Commercial Tower Office in Riyadh",
        titleAr: "مكتب في برج تجاري بالرياض",
        description: "High-end office space in King Abdullah Financial District.",
        descriptionAr: "مساحة مكتبية راقية في مركز الملك عبدالله المالي.",
        type: "rent",
        category: "office",
        price: 120000,
        priceUnit: "SAR/year",
        area: 400,
        country: "Saudi Arabia",
        city: "Riyadh",
        cityAr: "الرياض",
        address: "KAFD",
        addressAr: "مركز الملك عبدالله المالي",
        lat: 24.7648,
        lng: 46.6426,
        bedrooms: 0,
        bathrooms: 3,
        images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80"],
        featured: true,
        amenities: ["Conference Room", "High Speed Internet", "Valet Parking"],
        amenitiesAr: ["قاعة مؤتمرات", "إنترنت فائق السرعة", "خدمة صف السيارات"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 14,
        title: "Garden Villa in Mecca",
        titleAr: "فيلا بحديقة في مكة المكرمة",
        description: "Peaceful villa with a large garden, minutes from the Holy Mosque.",
        descriptionAr: "فيلا هادئة بحديقة واسعة على بعد دقائق من المسجد الحرام.",
        type: "sale",
        category: "villa",
        price: 6500000,
        priceUnit: "SAR",
        area: 600,
        country: "Saudi Arabia",
        city: "Mecca",
        cityAr: "مكة المكرمة",
        address: "Al Aziziyah",
        addressAr: "العزيزية",
        lat: 21.3891,
        lng: 39.8579,
        bedrooms: 7,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1564507593729-f6e2e32c1e27?w=800&q=80"],
        featured: false,
        amenities: ["Large Garden", "Parking", "Near Haram"],
        amenitiesAr: ["حديقة كبيرة", "مواقف", "قريب من الحرم"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 15,
        title: "Studio Apartment in Medina",
        titleAr: "استوديو في المدينة المنورة",
        description: "Cozy furnished studio near Al Masjid Al Nabawi.",
        descriptionAr: "استوديو مفروش ومريح بالقرب من المسجد النبوي.",
        type: "rent",
        category: "apartment",
        price: 22000,
        priceUnit: "SAR/year",
        area: 55,
        country: "Saudi Arabia",
        city: "Medina",
        cityAr: "المدينة المنورة",
        address: "Central Area",
        addressAr: "المنطقة المركزية",
        lat: 24.4672,
        lng: 39.6024,
        bedrooms: 1,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80"],
        featured: false,
        amenities: ["Fully Furnished", "Near Prophet's Mosque"],
        amenitiesAr: ["مفروش بالكامل", "قريب من المسجد النبوي"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 16,
        title: "Investment Land in Jeddah",
        titleAr: "أرض استثمارية في جدة",
        description: "Excellent investment opportunity — residential land in north Jeddah.",
        descriptionAr: "فرصة استثمارية ممتازة — أرض سكنية في شمال جدة.",
        type: "sale",
        category: "land",
        price: 3200000,
        priceUnit: "SAR",
        area: 800,
        country: "Saudi Arabia",
        city: "Jeddah",
        cityAr: "جدة",
        address: "Obhur",
        addressAr: "أبحر",
        lat: 21.7259,
        lng: 39.1040,
        bedrooms: 0,
        bathrooms: 0,
        images: ["https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80"],
        featured: false,
        amenities: ["Residential Zoning", "Near Highway"],
        amenitiesAr: ["تصنيف سكني", "قريب من الطريق السريع"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 17,
        title: "Waterfront Apartment in Dhahran",
        titleAr: "شقة على الواجهة البحرية في الظهران",
        description: "Modern apartment overlooking the waterfront promenade in Dhahran.",
        descriptionAr: "شقة حديثة تطل على الممشى البحري في الظهران.",
        type: "rent",
        category: "apartment",
        price: 48000,
        priceUnit: "SAR/year",
        area: 170,
        country: "Saudi Arabia",
        city: "Dhahran",
        cityAr: "الظهران",
        address: "Dammam Waterfront",
        addressAr: "واجهة الدمام البحرية",
        lat: 26.2361,
        lng: 50.0393,
        bedrooms: 3,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=800&q=80"],
        featured: false,
        amenities: ["Waterfront View", "Gym", "Pool"],
        amenitiesAr: ["إطلالة بحرية", "نادي رياضي", "مسبح"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 18,
        title: "Luxury Compound Villa in Riyadh",
        titleAr: "فيلا كمبوند فاخرة في الرياض",
        description: "Gated compound villa with world-class amenities and 24/7 security.",
        descriptionAr: "فيلا داخل كمبوند محاط بالأسوار مع خدمات عالمية المستوى وأمن على مدار الساعة.",
        type: "rent",
        category: "villa",
        price: 180000,
        priceUnit: "SAR/year",
        area: 350,
        country: "Saudi Arabia",
        city: "Riyadh",
        cityAr: "الرياض",
        address: "Diplomatic Quarter",
        addressAr: "الحي الدبلوماسي",
        lat: 24.6715,
        lng: 46.6204,
        bedrooms: 4,
        bathrooms: 4,
        images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80"],
        featured: true,
        amenities: ["Compound", "24/7 Security", "Pool", "Tennis Court"],
        amenitiesAr: ["كمبوند", "أمن 24/7", "مسبح", "ملعب تنس"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 19,
        title: "Commercial Shop in Cairo",
        titleAr: "محل تجاري في القاهرة",
        description: "High-traffic commercial shop in downtown Cairo, ideal for retail.",
        descriptionAr: "محل تجاري في وسط القاهرة بحركة مرور عالية، مثالي للبيع بالتجزئة.",
        type: "rent",
        category: "commercial",
        price: 35000,
        priceUnit: "EGP/month",
        area: 90,
        country: "Egypt",
        city: "Cairo",
        cityAr: "القاهرة",
        address: "Downtown Cairo",
        addressAr: "وسط البلد",
        lat: 30.0459,
        lng: 31.2386,
        bedrooms: 0,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80"],
        featured: false,
        amenities: ["Street Facing", "Storage Room"],
        amenitiesAr: ["واجهة على الشارع", "مخزن"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 20,
        title: "Twin Villa in Khobar",
        titleAr: "فيلا توين في الخبر",
        description: "Elegant twin villa with premium design in Al Khobar's finest neighborhood.",
        descriptionAr: "فيلا توين أنيقة بتصميم راقي في أفضل أحياء الخبر.",
        type: "sale",
        category: "villa",
        price: 4800000,
        priceUnit: "SAR",
        area: 380,
        country: "Saudi Arabia",
        city: "Khobar",
        cityAr: "الخبر",
        address: "Al Aqrabiyah",
        addressAr: "العقربية",
        lat: 26.2790,
        lng: 50.2084,
        bedrooms: 5,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80"],
        featured: false,
        amenities: ["Driver Room", "Maid Room", "Garden"],
        amenitiesAr: ["غرفة سائق", "غرفة خادمة", "حديقة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 21,
        title: "Modern Loft in Alexandria",
        titleAr: "لوفت عصري في الإسكندرية",
        description: "Stylish open-plan loft in the vibrant heart of Alexandria.",
        descriptionAr: "لوفت أنيق بتصميم مفتوح في قلب الإسكندرية النابض بالحياة.",
        type: "rent",
        category: "apartment",
        price: 12000,
        priceUnit: "EGP/month",
        area: 110,
        country: "Egypt",
        city: "Alexandria",
        cityAr: "الإسكندرية",
        address: "Stanley",
        addressAr: "ستانلي",
        lat: 31.2395,
        lng: 29.9664,
        bedrooms: 1,
        bathrooms: 1,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80"],
        featured: false,
        amenities: ["Open Plan", "High Ceiling", "Furnished"],
        amenitiesAr: ["تصميم مفتوح", "سقف عالي", "مفروش"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 22,
        title: "Executive Suite in Dammam",
        titleAr: "جناح تنفيذي في الدمام",
        description: "Fully serviced executive apartment in a 5-star tower.",
        descriptionAr: "شقة تنفيذية مخدومة بالكامل في برج 5 نجوم.",
        type: "rent",
        category: "apartment",
        price: 75000,
        priceUnit: "SAR/year",
        area: 140,
        country: "Saudi Arabia",
        city: "Dammam",
        cityAr: "الدمام",
        address: "Business District",
        addressAr: "حي الأعمال",
        lat: 26.4207,
        lng: 50.0888,
        bedrooms: 2,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80"],
        featured: false,
        amenities: ["Room Service", "Business Center", "Valet"],
        amenitiesAr: ["خدمة الغرف", "مركز أعمال", "خدمة صف السيارات"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 23,
        title: "Pyramids View Villa in Giza",
        titleAr: "فيلا بإطلالة على الأهرامات في الجيزة",
        description: "Once-in-a-lifetime opportunity — villa with direct Pyramids views.",
        descriptionAr: "فرصة العمر — فيلا بإطلالة مباشرة على الأهرامات.",
        type: "sale",
        category: "villa",
        price: 15000000,
        priceUnit: "EGP",
        area: 500,
        country: "Egypt",
        city: "Giza",
        cityAr: "الجيزة",
        address: "Haram Road",
        addressAr: "شارع الهرم",
        lat: 29.9792,
        lng: 31.1342,
        bedrooms: 6,
        bathrooms: 5,
        images: ["https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80"],
        featured: true,
        amenities: ["Pyramids View", "Pool", "Private Garden", "Security"],
        amenitiesAr: ["إطلالة على الأهرامات", "مسبح", "حديقة خاصة", "حراسة"],
        createdAt: new Date().toISOString(),
    },
    {
        id: 24,
        title: "Medical Office in Jeddah",
        titleAr: "عيادة طبية في جدة",
        description: "Licensed medical office space in a healthcare complex.",
        descriptionAr: "عيادة طبية مرخصة في مجمع طبي متكامل.",
        type: "rent",
        category: "office",
        price: 80000,
        priceUnit: "SAR/year",
        area: 180,
        country: "Saudi Arabia",
        city: "Jeddah",
        cityAr: "جدة",
        address: "Al Safa",
        addressAr: "الصفا",
        lat: 21.5169,
        lng: 39.2192,
        bedrooms: 0,
        bathrooms: 2,
        images: ["https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80"],
        featured: false,
        amenities: ["Medical License", "Waiting Area", "Elevator"],
        amenitiesAr: ["رخصة طبية", "صالة انتظار", "مصعد"],
        createdAt: new Date().toISOString(),
    },
];

export const MOCK_STATS_SUMMARY: StatsSummary = {
    totalProperties: MOCK_PROPERTIES.length,
    forSale: MOCK_PROPERTIES.filter(p => p.type === 'sale').length,
    forRent: MOCK_PROPERTIES.filter(p => p.type === 'rent').length,
    avgPriceSale: Math.round(MOCK_PROPERTIES.filter(p => p.type === 'sale').reduce((a, b) => a + b.price, 0) / Math.max(MOCK_PROPERTIES.filter(p => p.type === 'sale').length, 1)),
    avgPriceRent: Math.round(MOCK_PROPERTIES.filter(p => p.type === 'rent').reduce((a, b) => a + b.price, 0) / Math.max(MOCK_PROPERTIES.filter(p => p.type === 'rent').length, 1)),
    totalCities: new Set(MOCK_PROPERTIES.map(p => p.city)).size,
    newThisMonth: MOCK_PROPERTIES.length,
};

export const MOCK_CITIES: CityStats[] = Array.from(new Set(MOCK_PROPERTIES.map(p => p.city))).map(city => {
    const prop = MOCK_PROPERTIES.find(p => p.city === city)!;
    return {
        city: prop.city,
        cityAr: prop.cityAr,
        count: MOCK_PROPERTIES.filter(p => p.city === city).length
    };
});
